name = "omnidrive-family-api"
main = "src/index.ts"
compatibility_date = "2025-06-01"
compatibility_flags = [ "nodejs_compat_v2" ]

[triggers]
crons = ["*/30 * * * *"]

[[d1_databases]]
binding = "DB"
database_name = "omnidrive"
database_id = "a0b8d7a2-009c-42ec-8dd5-c721d9285866"

[[kv_namespaces]]
binding = "KV"
id = "32ee25caf762400b856b27569c6b3e5b"

[vars]
FRONTEND_URL = "https://omnidrive-family-web.pages.dev"
WORKER_URL = "https://omnidrive-family-api.golamirreza19954312.workers.dev"

[observability]
enabled = false
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = false
persist = true
head_sampling_rate = 1
